class printWaspNest() {
    println("")
    println("  ^^      .-=-=-=-.  ^^")
    println("^^      (`-=-=-=-=-`)         ^^")
    println("      (`-=-=-=-=-=-=-`)  ^^         ^^")
    println("^^   (`-=-=-=-=-=-=-=-`)   ^^                            ^^")
    println("    ( `-=-=-=-(@)-=-=-` )      ^^")
    println("    (`-=-=-=-=-=-=-=-=-`)  ^^")
    println("    (`-=-=-=-=-=-=-=-=-`)              ^^")
    println("    (`-=-=-=-=-=-=-=-=-`)                      ^^")
    println("    (`-=-=-=-=-=-=-=-=-`)  ^^")
    println("     (`-=-=-=-=-=-=-=-`)          ^^")
    println("      (`-=-=-=-=-=-=-`)  ^^                 ^^")
    println("  jgs   (`-=-=-=-=-`)")
    println("         `-=-=-=-=-`")
    println("")
    }

class printWasp() {
    println("")
    println("                                   ...vvvv)))))).")
    println("  /~~               ,,,c(((((((((((((((((/")
    println(" /~~c  .         .vv)))))))))))))))))))``")
    println("     G_G__   ,,((CCCC//////////////'")
    println("   ,Z~__ '@,gW@@AKXX~MW,gmmmz==m_.")
    println("  iP,dW@!,A@@@@@@@@@@@@@@@A` ,W@@Ac")
    println("  ]b_.__zf !P~@@@@@*P~b.~+=m@@@*~ g@Ws.")
    println("     ~`    ,2W2m. '[ ['~~c'M7 _gW@@A`'s")
    println("       v=XX)====Y-  [ [    c/*@@@*~ g@@i")
    println("      /v~           !.!.     'c7+sg@@@@@s.")
    println("     //              'c'c       'c7*X7~~~~")
    println("    ]/                 ~=Xm_       '~=(Gm_.")
    println("")
}

class printBalloon() {
    println("")
    println("        ,,,,,,,,,,,,,")
    println("    .;;;;;;;;;;;;;;;;;;;,.")
    println("  .;;;;;;;;;;;;;;;;;;;;;;;;,")
    println(".;;;;;;;;;;;;;;;;;;;;;;;;;;;;.")
    println(";;;;;@;;;;;;;;;;;;;;;;;;;;;;;;' .............")
    println(";;;;@@;;;;;;;;;;;;;;;;;;;;;;;;'.................")
    println(";;;;@@;;;;;;;;;;;;;;;;;;;;;;;;'...................")
    println("`;;;;@;;;;;;;;;;;;;;;@;;;;;;;'.....................")
    println(" `;;;;;;;;;;;;;;;;;;;@@;;;;;'..................;....")
    println("   `;;;;;;;;;;;;;;;;@@;;;;'....................;;...")
    println("     `;;;;;;;;;;;;;@;;;;'...;.................;;....")
    println("        `;;;;;;;;;;;;'   ...;;...............;.....")
    println("           `;;;;;;'        ...;;..................")
    println("              ;;              ..;...............")
    println("              `                  ............")
    println("             `                      ......")
    println("            `                         ..")
    println("           `                           '")
    println("          `                           '")
    println("         `                           '")
    println("        `                           `")
    println("        `                           `,")
    println("        `")
    println("         `")
    println("           `.")
    println("")
}

class printBlast() {
    println("")
    println("   !BLAM!    ")
    println("*     *    *")
    println("   * *** * ")
    println("* * *   * * *")
    println("   * *** *  ")
    println(" *    *   * ")
    println("")
}

class printSkull(){
println("         .... NO! ...                  ... MNO! ...")
println("   ..... MNO!! ...................... MNNOO! ...")
println(" ..... MMNO! ......................... MNNOO!! .")
println("..... MNOONNOO!   MMMMMMMMMMPPPOII!   MNNO!!!! .")
println(" ... !O! NNO! MMMMMMMMMMMMMPPPOOOII!! NO! ....")
println("    ...... ! MMMMMMMMMMMMMPPPPOOOOIII! ! ...")
println("   ........ MMMMMMMMMMMMPPPPPOOOOOOII!! .....")
println("   ........ MMMMMOOOOOOPPPPPPPPOOOOMII! ...")
println("    ....... MMMMM..    OPPMMP    .,OMI! ....")
println("     ...... MMMM::   o.,OPMP,.o   ::I!! ...")
println("         .... NNM:::.,,OOPM!P,.::::!! ....")
println("          .. MMNNNNNOOOOPMO!!IIPPO!!O! .....")
println("         ... MMMMMNNNNOO:!!:!!IPPPPOO! ....")
println("           .. MMMMMNNOOMMNNIIIPPPOO!! ......")
println("          ...... MMMONNMMNNNIIIOO!..........")
println("       ....... MN MOMMMNNNIIIIIO! OO ..........")
println("    ......... MNO! IiiiiiiiiiiiI OOOO ...........")
println("  ...... NNN.MNO! . O!!!!!!!!!O . OONO NO! ........")
println("   .... MNNNNNO! ...OOOOOOOOOOO .  MMNNON!........")
println("   ...... MNNNNO! .. PPPPPPPPP .. MMNON!........")
println("      ...... OO! ................. ON! .......")
println("         ................................")
}